### ISSUE TITLE
Does not find Fortran netCDF on strand

### ISSUE THREAD

**Issue by platipodium** [pvelissariou1/ADC-WW3-NWM-SCHISM-NEMS#1]
when issuing build -plat strand I get

```
### Configuring NetCDF
DEBUGNetCDF_C_INCLUDE_FILE: /usr/include/netcdf.h
DEBUGNetCDF_C_CONFIG_EXECUTABLE: /usr/include/../bin/nc-config
DEBUGNetCDF_C_LIBRARY: /project/opt/software/netcdf/4.7.0/intel_2020.0/lib/libnetcdf.so
-- Found NetCDF: /usr/include (found version "4.3.3.1")
-- FindNetCDF defines targets:
--   - NetCDF_VERSION [4.3.3.1]
--   - NetCDF_PARALLEL [FALSE]
--   - NetCDF_C_CONFIG_EXECUTABLE [/usr/include/../bin/nc-config]
--   - NetCDF::NetCDF_C [SHARED] [Root: /usr] Lib: /project/opt/software/netcdf/4.7.0/intel_2020.0/lib/libnetcdf.so
--
### Assigning output directories for binaries (bin), modules (include) and libraries (lib)
--

```
It does not detect fortran netcdf

**Comment by platipodium** [comment]
This has been fixed upstream, please pull SCHISM

**Comment by pvelissariou1** [comment]
Hi, Carsten

Yes I have seen your fix. I think the problem is not fixed by just adding
the "Fortran" string
in that line. I'll be working tomorrow on the CMake files, including
FindNetCDF.cmake, to see what the issue(s)
are and how we can fix them. Let me try and discuss it on Wednesday.

Thank you
Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
USM - Stennis Space Center
cell: (205) 227-9141
email: ***@***.***

**Comment by platipodium** [comment]
Dear Takis,

I agree, my fix is not a generalisable one. If we found a better solution, that would be great!

**Comment by pvelissariou1** [comment]
Dear Carsten,

I'll be working on this today to see if it can be fixed. I modified the
cmake file(s) yesterday and it seems
that it can find the netcdf libraries properly on my local machine (using
the core linux netcdf installation -
no modules and no env. variables).

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
USM - Stennis Space Center
cell: (205) 227-9141
email: ***@***.***

**Comment by platipodium** [comment]
Works for me now on strand, thanks for fixing this.

**Comment by pvelissariou1** [comment]
Dear Carsten,

Thank you for the update, I thought it would fix all the issues.
We will talk about all these in the meeting today.

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
USM - Stennis Space Center
cell: (205) 227-9141
email: ***@***.***
